# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20161202_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='Latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='Longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
